image: maven:3.5-jdk-9-slim

services:
- selenium/standalone-chrome:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  selenium_remote_url: "http://selenium__standalone-chrome:4444/wd/hub/"

cache:
  paths:
  - .m2/repository/

test:
  stage: qa_check
  script:
  - mvn test-compile failsafe:integration-test -DseleniumGridUrl=http://selenium__standalone-chrome:4444/wd/hub/ "-DseleniumJsonCapabilities={'browserName':'chrome','chromeOptions':{'args':['disable-dev-shm-usage']}}" -DfitnesseSuiteToRun=NpoPomsSuite.Omgevingen.Acceptatie.TestScripts.DesktopDevice
  artifacts:
    when: always
    reports:
      junit:
      - target/failsafe-reports/TEST-*.xml
    paths:
    - target
    expire_in: 1 week

  tags:
  - specialisterren

stages:
- qa_check
